/*
Deployment script for DatawarehouseSucos

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DatawarehouseSucos"
:setvar DefaultFilePrefix "DatawarehouseSucos"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key f41c1c28-349d-46b4-baed-355080e0e810 is skipped, element [dbo].[Dim_Categoria].[Id] (SqlSimpleColumn) will not be renamed to Cod_Categoria';


GO
PRINT N'Rename refactoring operation with key 0691c2e2-f235-46bf-af89-9e5cbdf7ddf7 is skipped, element [dbo].[Dim_marca].[Id] (SqlSimpleColumn) will not be renamed to Cod_Marca';


GO
PRINT N'Rename refactoring operation with key fc505dc9-9086-403c-a017-830d7c2e329c is skipped, element [dbo].[FK_Dim_marca_ToTable] (SqlForeignKeyConstraint) will not be renamed to [FK_Dim_marca_Dim_Categoria]';


GO
PRINT N'Rename refactoring operation with key aa3241aa-a77f-4b85-ad9c-e0a8cda7da70 is skipped, element [dbo].[Dim_produto].[Id] (SqlSimpleColumn) will not be renamed to Cod_Produto';


GO
PRINT N'Creating [dbo].[Dim_Categoria]...';


GO
CREATE TABLE [dbo].[Dim_Categoria] (
    [Cod_Categoria]  NVARCHAR (50) NOT NULL,
    [Desc_Categoria] NCHAR (10)    NULL,
    PRIMARY KEY CLUSTERED ([Cod_Categoria] ASC)
);


GO
PRINT N'Creating [dbo].[Dim_marca]...';


GO
CREATE TABLE [dbo].[Dim_marca] (
    [Cod_Marca]     NVARCHAR (50)  NOT NULL,
    [Desc_Marca]    NVARCHAR (200) NULL,
    [Cod_Categoria] NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Cod_Marca] ASC)
);


GO
PRINT N'Creating [dbo].[Dim_produto]...';


GO
CREATE TABLE [dbo].[Dim_produto] (
    [Cod_Produto]  NVARCHAR (50)  NOT NULL,
    [Desc_Produto] NVARCHAR (200) NULL,
    [Atr_Tamanho]  NVARCHAR (200) NULL,
    [Atr_Sabor]    NVARCHAR (200) NULL,
    [Cod_Marca]    NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([Cod_Produto] ASC)
);


GO
PRINT N'Creating [dbo].[FK_Dim_marca_Dim_Categoria]...';


GO
ALTER TABLE [dbo].[Dim_marca] WITH NOCHECK
    ADD CONSTRAINT [FK_Dim_marca_Dim_Categoria] FOREIGN KEY ([Cod_Categoria]) REFERENCES [dbo].[Dim_Categoria] ([Cod_Categoria]);


GO
PRINT N'Creating [dbo].[FK_Dim_produto_Dim_Marca]...';


GO
ALTER TABLE [dbo].[Dim_produto] WITH NOCHECK
    ADD CONSTRAINT [FK_Dim_produto_Dim_Marca] FOREIGN KEY ([Cod_Marca]) REFERENCES [dbo].[Dim_marca] ([Cod_Marca]);


GO
-- Refactoring step to update target server with deployed transaction logs
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'f41c1c28-349d-46b4-baed-355080e0e810')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('f41c1c28-349d-46b4-baed-355080e0e810')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '0691c2e2-f235-46bf-af89-9e5cbdf7ddf7')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('0691c2e2-f235-46bf-af89-9e5cbdf7ddf7')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'fc505dc9-9086-403c-a017-830d7c2e329c')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('fc505dc9-9086-403c-a017-830d7c2e329c')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'aa3241aa-a77f-4b85-ad9c-e0a8cda7da70')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('aa3241aa-a77f-4b85-ad9c-e0a8cda7da70')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Dim_marca] WITH CHECK CHECK CONSTRAINT [FK_Dim_marca_Dim_Categoria];

ALTER TABLE [dbo].[Dim_produto] WITH CHECK CHECK CONSTRAINT [FK_Dim_produto_Dim_Marca];


GO
PRINT N'Update complete.';


GO
